version: 1.3.5.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  JETBRAINS_USERNAME:
    secure: po3BOWFNOw8YNCx3wfpJLQ==
  JETBRAINS_PASSWORD:
    secure: 7ol4pMcA1+XRRuuO6SQhGg==
build_script:
  - cmd: >-
      set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

      gradlew build_201

      gradlew build_202

      set JAVA_HOME=C:\Program Files\Java\jdk11

      gradlew build_203
artifacts:
  - path: build/distributions/*.zip